name: ocr
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  google_mlkit_text_recognition: ^0.11.0
  image_picker: ^1.0.4
  permission_handler: ^11.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_bloc: ^8.1.3
  dropdown_button2: ^2.3.9
  pinput: ^5.0.1
  google_fonts: ^6.1.0
  camera: ^0.10.5+9
  auto_route: ^9.3.0+1
  auto_route_generator: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
  
  assets:
    - assets/data/allergens.json
    
  fonts:
    - family: Oswald
      fonts:
        - asset: assets/fonts/Oswald-Regular.ttf
        - asset: assets/fonts/Oswald-Medium.ttf
          weight: 500
        - asset: assets/fonts/Oswald-Bold.ttf
          weight: 700
    
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

flutter_intl:
  enabled: true
  arb_dir: lib/l10n
  output_dir: lib/l10n/generated
